spring:
  application:
    name: library-api
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true